name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cisr
          python-version: 3.7
          channels: conda-forge
          channel-priority: flexible
          auto-update-conda: true
      
      - name: Install cisr
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Install dependencies
          conda install --yes -c anaconda mpi4py
          
      - name: Test with unittest
        run: |
          python -m unittest discover -v -s . -p "*test*.py"